import math

import torch
import torch.nn.functional as F
from torch import nn
from torch.nn.parameter import Buffer


class FourierPE(nn.Module):
    """
    Deterministic Fourier positional encoding.

    Given an input x in the current coordinate system, this module builds
    a multi-scale sinusoidal encoding using dyadic frequencies:

        freq_k = freq_max * (0.5 ** k),   k = 0, ..., num_bands - 1

    Here:
      - `freq_max` is the maximum frequency in cycles per unit,
      - lower bands decay geometrically by a factor of 2.

    Inputs:
      x: [N, in_dim]

    Output:
      enc: [N, 2 * in_dim * num_bands] (+ in_dim if include_input=True)

    Notes:
      - This module does not assume x is normalized to [-0.5, 0.5].
      - The meaning of one unit in x is determined entirely by the caller.
      - If include_input=False, only the sinusoidal features are returned.
      - If include_input=True, the raw coordinate is concatenated at the end.

    """

    def __init__(
        self,
        in_dim: int = 3,
        num_bands: int = 6,
        freq_max: float = 0.5,
        include_input: bool = False,
    ):
        super().__init__()
        self.in_dim = int(in_dim)
        self.num_bands = int(num_bands)
        self.freq_max = float(freq_max)
        self.include_input = bool(include_input)

        # Frequencies in cycles per unit, ordered from high to low.
        freqs = self.freq_max * (0.5 ** torch.arange(self.num_bands, dtype=torch.float32))  # [L]
        self.freqs = Buffer(freqs, persistent=True)

    @property
    def out_dim(self) -> int:
        base = 2 * self.in_dim * self.num_bands
        return base + (self.in_dim if self.include_input else 0)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.ndim != 2 or x.shape[1] != self.in_dim:
            raise ValueError(f"Expected x shape [N,{self.in_dim}], got {tuple(x.shape)}")
        if not torch.is_floating_point(x):
            x = x.float()

        x = x.to(self.freqs.dtype)
        # angles: 2π * f * x
        angles = (2.0 * math.pi) * x[:, :, None] * self.freqs[None, None, :]  # [N,3,L]
        angles = angles.reshape(x.shape[0], -1)  # [N, 3L]
        enc = torch.cat([torch.sin(angles), torch.cos(angles)], dim=-1)  # [N, 6L]

        if self.include_input:
            enc = torch.cat([enc, x], dim=-1)

        return enc


class RotaryPositionEmbedder(nn.Module):
    """
    Rotary positional embedding for attention q/k features.

    This module applies RoPE using a geometrically decaying set of angular
    frequencies:

        ang_freq_k = rope_scale / (rope_theta ** (k / freq_dim))

    Here:
      - `rope_scale` sets the maximum angular frequency,
      - `rope_theta` is the standard RoPE frequency base,
      - lower-frequency channels are generated by geometric decay.

    Attention with RoPE is computed by rotating q/k before the dot product:

        q_i^R = R(theta_i) q_i
        k_j^R = R(theta_j) k_j
        score_ij = <q_i^R, k_j^R> / sqrt(d)
        attn_ij = softmax_j(score_ij)
        out_i = sum_j attn_ij v_j

    The dot product depends on the relative phase theta_j - theta_i, which is
    how RoPE injects relative position information into attention.

    Inputs:
      x: [..., N, ..., H]
         Attention features to be rotated.
      x_pos: [..., N, in_channels]
         Coordinates associated with the N tokens.

    Output:
      x_embd: same shape as x

    Notes:
      - RoPE acts on q/k features, not directly on v.
      - The relative-position behavior comes from phase differences in q-k
        interactions.
      - `ang_freqs` is the same quantity commonly named `inv_freq` in RoPE
        implementations. It is multiplied directly with x_pos to produce
        angles in radians.
    """

    def __init__(
        self,
        hidden_size: int,
        in_channels: int = 3,
        rope_scale: float = 0.75,
        rope_theta: float = 10000.0,
    ) -> None:
        super().__init__()

        self.hidden_size = hidden_size
        self.in_channels = in_channels
        self.rope_scale = float(rope_scale)
        self.rope_theta = float(rope_theta)

        self.freq_dim = hidden_size // in_channels // 2

        freq_ids = torch.arange(self.freq_dim, dtype=torch.float32) / self.freq_dim
        ang_freqs = self.rope_scale / (self.rope_theta**freq_ids)

        self.ang_freqs = Buffer(ang_freqs, persistent=True)

    def forward(
        self,
        x: torch.Tensor,
        x_pos: torch.Tensor,
    ) -> torch.Tensor:
        """
        x: [..., N, ..., nhead, H]
        x_pos: [..., N, in_channels] float
        """
        Dh = x.shape[-1]
        assert Dh == self.hidden_size
        assert Dh % 2 == 0

        ang_freqs = self.ang_freqs.to(device=x.device, dtype=torch.float32)
        ang = x_pos[..., None].float() * ang_freqs  # [..., in_c, F]
        ang = ang.reshape(*ang.shape[:-2], -1)
        ang = F.pad(ang, (0, self.hidden_size // 2 - ang.shape[-1]), value=0.0)  # pad on last dim

        # ang original: [..., N, H//2]
        # x original: [..., N, ..., H]
        # ang new: [..., N, 1,1, ..., H//2]
        if x.ndim > x_pos.ndim:
            ang = ang.reshape(*x_pos.shape[:-1], *tuple([1] * (x.ndim - x_pos.ndim)), ang.shape[-1])

        cos = ang.cos()
        sin = ang.sin()

        x1 = x[..., 0::2].float()
        x2 = x[..., 1::2].float()
        y1 = x1 * cos - x2 * sin
        y2 = x1 * sin + x2 * cos

        x_embd = torch.stack((y1, y2), dim=-1).flatten(-2).to(x.dtype)

        return x_embd
