"""SAM3D Objects-specific inference constants."""

# Official SAM3D Objects sampler defaults expressed in SymTRELLIS flow/CFG convention.
SAM3D_OBJECTS_SPARSE_STRUCTURE_STEPS = 25
SAM3D_OBJECTS_SPARSE_STRUCTURE_RESCALE_T = 3.0
SAM3D_OBJECTS_SPARSE_STRUCTURE_CFG_STRENGTH = 8.0
SAM3D_OBJECTS_SPARSE_STRUCTURE_CFG_INTERVAL = (0.0, 0.5)
SAM3D_OBJECTS_SPARSE_STRUCTURE_CFG_RESCALE = 0.0
SAM3D_OBJECTS_SPARSE_STRUCTURE_POINTMAP_CFG_STRENGTH = 0.0

SAM3D_OBJECTS_SLAT_STEPS = 25
SAM3D_OBJECTS_SLAT_RESCALE_T = 3.0
SAM3D_OBJECTS_SLAT_CFG_STRENGTH = 6.0
SAM3D_OBJECTS_SLAT_CFG_INTERVAL = (0.0, 0.5)
SAM3D_OBJECTS_SLAT_CFG_RESCALE = 0.0


__all__ = [
    "SAM3D_OBJECTS_SLAT_CFG_INTERVAL",
    "SAM3D_OBJECTS_SLAT_CFG_RESCALE",
    "SAM3D_OBJECTS_SLAT_CFG_STRENGTH",
    "SAM3D_OBJECTS_SLAT_RESCALE_T",
    "SAM3D_OBJECTS_SLAT_STEPS",
    "SAM3D_OBJECTS_SPARSE_STRUCTURE_CFG_INTERVAL",
    "SAM3D_OBJECTS_SPARSE_STRUCTURE_CFG_RESCALE",
    "SAM3D_OBJECTS_SPARSE_STRUCTURE_CFG_STRENGTH",
    "SAM3D_OBJECTS_SPARSE_STRUCTURE_POINTMAP_CFG_STRENGTH",
    "SAM3D_OBJECTS_SPARSE_STRUCTURE_RESCALE_T",
    "SAM3D_OBJECTS_SPARSE_STRUCTURE_STEPS",
]
